# Generated by Django 3.2.19 on 2023-05-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_measure_unit_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фотографию готового блюда', upload_to='recipes/images', verbose_name='Фотография блюда'),
        ),
    ]
